### ISSUE TITLE
dc is crashing when it connects

### ISSUE THREAD

**Issue by joefowler** [usnistgov/dastard-commander#2]
```text
fowlerj@817jfmac:dastard-commander$ ./dc.py 
Dastard is at localhost:5500
Collecting updates from dastard
STATUS     0: JSON: {u'SourceName': u'', u'Running': False, u'Nsamples': 0, u'Npresamp': 0, u'Nchannels': 0}
Here we tell the server records are 4 (3 pretrigger)
Yikes! Request is:  {'params': [{'Nsamp': 4, 'Npre': 3}], 'method': 'SourceControl.ConfigurePulseLengths', 'id': 1}
Reponse is:  {u'error': u'No source is active', u'id': 1, u'result': None}
Traceback (most recent call last):
  File "./dc.py", line 105, in updateRecordLengths
    self.client.call("SourceControl.ConfigurePulseLengths", {"Nsamp":samp, "Npre":presamp})
  File "/Users/fowlerj/Software/dastard-commander/rpc_client.py", line 35, in call
    raise Exception(response.get('error'))
Exception: No source is active
Abort trap: 6
```

**Comment by joefowler** [comment]
This doesn't happen if the server is already Running=True when dc starts. It must have to do with sending state from dc to server before dc is ready to do so. (Shouldn't be sending nsamples if not running.)
