### ISSUE TITLE
DC should recover when the RPC server (dastard) restarts

### ISSUE THREAD

**Issue by joefowler** [usnistgov/dastard-commander#35]
Currently, if you start dastard and then commander, then _restart_ dastard, you get a hard crash of commander because the RPC server it expects to talk to has died. Possible improvements:

1. Detect this error, and go back to the tiny dialog window where you get to reconnect. (simple but less awesome)

2. Detect this error, automatically attempt to reconnect (assume the same host:port as before). If it works, then the user never need know it happened. If not, fall back to the reconnection dialog. (less simple but more awesome)

**Comment by joefowler** [comment]
I should be clear: the hard crash happens only when commander next tries to issue an RPC command, not before.

**Comment by joefowler** [comment]
A typical stack trace:

```text
Traceback (most recent call last):
  File "/Users/fowlerj/Software/dastard-commander/trigger_config.py", line 62, in go1psMode
    self.changedAllTrigConfig()
  File "/Users/fowlerj/Software/dastard-commander/trigger_config.py", line 252, in changedAllTrigConfig
    self.changedAutoTrigConfig()
  File "/Users/fowlerj/Software/dastard-commander/trigger_config.py", line 270, in changedAutoTrigConfig
    self.client.call("SourceControl.ConfigureTriggers", state)
  File "/Users/fowlerj/Software/dastard-commander/rpc_client.py", line 44, in call
    response = self._codec.loads(response.decode())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_dec
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Abort trap: 6
```

**Comment by joefowler** [comment]
I can implement idea 1, above: catch RPC call errors and automatically shut down the client and close the main window. That's not so hard. 

But after further reflection, I think automatic reconnection (idea 2) is not ideal. Some button clicks (e.g. any that change the trigger state) can make multiple RPC calls. If the first one fails, then you don't want to reconnect and then make the remaining calls. More to the point, if dastard has--unbeknownst to you--restarted, then its state might not be what you think, and the button press action might not be the right one.

The better solution would be to have a new instance of dastard send a special message to say "I am new". (Is there already such a message?) Commander would then respond by attempting to re-make the connection. That would most easily be done by closing the main window. So I'll work on that....

**Comment by ggggggggg** [comment]
I am new message sounds fine. Maybe have a counter associated with each heartbeat message or each message at all, and when the counter is 0 or went down you know dastard is new? Though at that point, it's kind of like my ID idea.
