### ISSUE TITLE
Cannot connect latest master version to dastard

### ISSUE THREAD

**Issue by joefowler** [usnistgov/dastard-commander#36]
When I connect the latest master version to a dastard running the current version of master, I get a crash:

```text
Dastard is at localhost:5500
Traceback (most recent call last):
  File "./dc.py", line 675, in <module>
    main()
  File "./dc.py", line 665, in main
    dc = MainWindow(client, host, port)
  File "./dc.py", line 83, in __init__
    self.workflowTab = workflow.Workflow(self, parent=self.ui.tabWorkflow)
  File "/Users/fowlerj/Software/dastard-commander/workflow.py", line 90, in __init__
    self.uipushButton_takeNoise.setEnabled(False)
AttributeError: 'Workflow' object has no attribute 'uipushButton_takeNoise'
```

**Comment by joefowler** [comment]
Oops. This was my bug. Not sure why you didn't have the same problems I had with it.
