### ISSUE TITLE
map related crash

### ISSUE THREAD

**Issue by ggggggggg** [usnistgov/dastard-commander#49]
I got this when I switched from lancero source to simluated source, but I haven't been able to replicate.

```Traceback (most recent call last):
  File "dc.py", line 145, in updateReceived
    self.observeTab.handleTriggerRateMessage(d)
  File "/home/pcuser/dastard-commander/observe.py", line 46, in handleTriggerRateMessage
    self.buildCRM()
  File "/home/pcuser/dastard-commander/observe.py", line 95, in buildCRM
    self.crm_grid = CountRateMap(self, self.cols, self.rows, self.getChannelNames())
  File "/home/pcuser/dastard-commander/observe.py", line 90, in getChannelNames
    assert(len(channel_names) == cols*rows*(1+self.auxPerChan))
AssertionError
Aborted (core dumped)
```

**Comment by joefowler** [comment]
I can't replicate either. Not sure what to do about it.

**Comment by ggggggggg** [comment]
You can close it, it's not a very good report.

**Comment by joefowler** [comment]
Cannot replicate. Reopen if you figure out how to replicate.
